# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: write
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      run: |
        # Get the clean tag name (e.g., v1.2.3), fallback to the short commit SHA if no tag exists
        VERSION=${GITHUB_REF_NAME:-$(git rev-parse --short HEAD)}
        
        # Build and inject the version into the 'main' package
        go build -v -ldflags "-X main.Version=${VERSION}" -o bin/ ./...

    - name: Test
      run: go test -v ./...
      
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
